import os
import logging
from typing import Optional
from app.models.result import ExplanationResponse

logger = logging.getLogger(__name__)


class GeminiService:
    """Gemini AI service for explaining eligibility results.
    
    IMPORTANT: Gemini is ONLY used for explanation.
    It MUST NOT decide eligibility, override rules, or invent policies.
    """
    
    def __init__(self):
        self.api_key = os.getenv('GEMINI_API_KEY')
        self.model = None
        if self.api_key:
            try:
                import google.generativeai as genai
                genai.configure(api_key=self.api_key)
                self.model = genai.GenerativeModel('gemini-3.6-flash')
                logger.info('Gemini API configured successfully.')
            except Exception as e:
                logger.warning(f'Failed to configure Gemini: {e}')
    
    def explain_results(
        self,
        student_profile: dict,
        eligibility_result: dict,
        recommendation_result: dict = None
    ) -> ExplanationResponse:
        """Explain eligibility and recommendation results using Gemini or fallback."""
        if not self.model:
            return self._fallback_explanation(student_profile, eligibility_result, recommendation_result)
        
        try:
            prompt = self._build_prompt(student_profile, eligibility_result, recommendation_result)
            response = self.model.generate_content(prompt)
            
            explanation = response.text if response.text else 'Unable to generate explanation.'
            
            notes = [
                'This explanation is generated by AI based on deterministic rule-engine results.',
                'All eligibility decisions are made by the rule engine, not by AI.',
                'Scheme data used is demo/sample data. Verify against current government notifications.'
            ]
            
            return ExplanationResponse(
                explanation=explanation,
                important_notes=notes
            )
        except Exception as e:
            logger.error(f'Gemini API error: {e}')
            return self._fallback_explanation(student_profile, eligibility_result, recommendation_result)
    
    def _build_prompt(self, profile: dict, eligibility: dict, recommendation: dict = None) -> str:
        """Build a constrained prompt for Gemini."""
        prompt = (
            'You are an explanation assistant for a Tamil Nadu student scholarship eligibility system.\n\n'
            'STRICT RULES:\n'
            '1. The eligibility decisions below were produced by a deterministic rule engine.\n'
            '2. Do NOT change, reinterpret, or override those decisions.\n'
            '3. Explain ONLY the supplied results in simple, student-friendly language.\n'
            '4. If information is missing, say it is unavailable.\n'
            '5. Do NOT invent new schemes, benefits, or eligibility criteria.\n'
            '6. Use a friendly, helpful tone.\n'
            '7. Keep the explanation concise (under 500 words).\n\n'
            f'STUDENT PROFILE:\n{self._format_dict(profile)}\n\n'
            f'ELIGIBILITY RESULTS:\n{self._format_dict(eligibility)}\n'
        )
        
        if recommendation:
            prompt += f'\nRECOMMENDATION RESULTS:\n{self._format_dict(recommendation)}\n'
        
        prompt += (
            '\nPlease provide:\n'
            '1. A brief summary of the student\'s eligibility status.\n'
            '2. For each eligible scheme, explain why the student qualifies.\n'
            '3. For non-eligible schemes, briefly explain what conditions were not met.\n'
            '4. If recommendations are provided, explain why those schemes were recommended together.\n'
            '5. Any important notes about demo data status.\n'
        )
        
        return prompt
    
    def _format_dict(self, d: dict, indent: int = 2) -> str:
        """Format a dict for prompt inclusion."""
        import json
        return json.dumps(d, indent=indent, default=str)
    
    def _fallback_explanation(
        self,
        profile: dict,
        eligibility: dict,
        recommendation: dict = None
    ) -> ExplanationResponse:
        """Generate a basic explanation without Gemini."""
        parts = []
        
        student_name = profile.get('name', 'Student')
        parts.append(f'Eligibility Summary for {student_name}:')
        parts.append('')
        
        # Eligible schemes
        eligible = eligibility.get('eligible_schemes', [])
        if eligible:
            parts.append(f'✅ Eligible for {len(eligible)} scheme(s):')
            for scheme in eligible:
                name = scheme.get('scheme_name', scheme.get('scheme_id', 'Unknown'))
                parts.append(f'  - {name}')
                matched = scheme.get('matched_conditions', [])
                if matched:
                    parts.append(f'    Matched: {", ".join(matched[:3])}')
            parts.append('')
        
        # Not eligible
        not_eligible = eligibility.get('not_eligible_schemes', [])
        if not_eligible:
            parts.append(f'❌ Not eligible for {len(not_eligible)} scheme(s):')
            for scheme in not_eligible:
                name = scheme.get('scheme_name', scheme.get('scheme_id', 'Unknown'))
                failed = scheme.get('failed_conditions', [])
                parts.append(f'  - {name}')
                if failed:
                    parts.append(f'    Reason: {", ".join(failed[:2])}')
            parts.append('')
        
        # Recommendations
        if recommendation:
            rec_schemes = recommendation.get('recommended_schemes', [])
            if rec_schemes:
                total = recommendation.get('total_benefit', 0)
                parts.append(f'🎯 Recommended combination (estimated total benefit: ₹{total:,.0f}):')
                for s in rec_schemes:
                    parts.append(f'  - {s.get("scheme_name", "Unknown")} (₹{s.get("benefit_amount", 0):,.0f})')
        
        notes = [
            'GEMINI_API_KEY not configured. This is a basic rule-based explanation.',
            'All eligibility decisions are made by the deterministic rule engine.',
            'Scheme data is demo/sample data. Verify against current government notifications.'
        ]
        
        return ExplanationResponse(
            explanation='\n'.join(parts),
            important_notes=notes
        )
